blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/sundayz-hunter/BB_User_Agent/blob/master/README.md
    about: Check out the documentation before creating an issue
