name: 💡 Feature Request
description: Suggest an idea or enhancement for this project
title: "feat: "
labels: ["enhancement"]
body:
- type: textarea
  attributes:
    label: Expected feature
    description: A clear and concise description of what the problem is and how it could be approached.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternative Solutions
    description: Describe any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Implementation Details
    description: If you have ideas about how to implement this feature, share them here.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context, screenshots, or mockups about the feature request here.
      
      Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  id: acknowledgements
  attributes:
    label: Acknowledgements
    description: Please confirm the following before submitting your feature request.
    options:
      - label: I have searched existing issues and this feature has not been requested yet.
        required: true
      - label: This is a single feature (not multiple features combined into one request).
        required: true
      - label: I have provided sufficient information to understand the proposed feature.
        required: true